networks:
  backend:

volumes:
  db-data:

secrets:
  db_password:
    file: ./db_password.txt

services:
  api:
    container_name: api
    image: backend
    build:
      context: ./Backend/DaDoIS.Api/
      dockerfile: Dockerfile
    ports: 
      - "5002:8080"
    networks:
      - backend
    depends_on:
      - database

  database:
    container_name: mssql
    image: mcr.microsoft.com/mssql/server:latest
    environment:
      ACCEPT_EULA: Y
      MSSQL_SA_PASSWORD_FILE: /run/secrets/db_password
    secrets:
      - db_password
    ports:
      - "5001:1433"
    volumes:
      - db-data:/var/opt/mssql
    networks:
      - backend
